
title: Intensive Community Outreach Services
email: info@icoservices.org
description: >- # this means to ignore newlines until "baseurl:"
  ICOS is dedicated to assisting adolescents and adults with mental illness through working toward greater independence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.icoservices.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: /blog/:title/
theme: minima
plugins:
  - jekyll-feed

collections:
  programs:
    output: true
    permalink: /programs/:title/

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
