
title: Intensive Care Outpatient Services
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  At ICOS, our primary purpose is to identify at-risk individuals in the community and provide quality services
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: /blog/:title/
theme: minima
plugins:
  - jekyll-feed

collections:
  programs:
    output: true
    permalink: /programs/:title/

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
