- value: Confidentiality
  value-description: We strive to provide our clients with peace of mind through industry best practices.
  font: "0"
- value: Integrity
  value-description: Ethics, character and values are what we are about at ICOS.
  font: "o"
- value: Loyalty
  value-description: We remain loyal to our clients as we assist them to reach their life goals.
  font: "~"
- value: Unity
  value-description: Here at ICOS everyone is treated as family.
  font: "l"